# Source: airflow/templates/deployments-scheduler.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow-test
  template:
    metadata:
       labels:
         name: airflow-test
    spec:
      restartPolicy: Always
      serviceAccountName: airflow
      volumes:
        - name: airflow-configmap
          configMap:
            name: airflow-configmap
      containers:
        - name: airflow-scheduler
          image: apache/airflow:1.10.10
          volumeMounts:
          - name: airflow-configmap
            mountPath: /opt/airflow/airflow.cfg
            subPath: airflow.cfg
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: "airflow-env"
          env:          
            - name: POSTGRES_USER
              value: "postgres"
          command:
            - "bash"
            - "-c"
            - >
              ls -l ${AIRFLOW_HOME}/airflow.cfg &&
              env && 
              echo 'waiting 10s...' &&
              sleep 2 &&
              mkdir -p /opt/airflow/.local/bin &&
              export PATH=/opt/airflow/.local/bin:$PATH &&
              echo "executing initdb" &&
              airflow initdb &&
              echo "executing scheduler" &&
              airflow scheduler -n -1