# Source: airflow/templates/configmap-env.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "airflow-env"
  labels:
    app: airflow
    chart: airflow-0.1
    release: airflow
    heritage: Helm
data:
  ## Force UTC timezone
  TZ: Etc/UTC
  ## Postgres DB configuration
  # POSTGRES_HOST: "postgres-service.default.svc.cluster.local"
  # POSTGRES_PORT: "5432"
  # POSTGRES_DB: "airflow"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:abc123@postgres-service.default.svc.cluster.local:5432/airflow"
  FERNET_KEY: "SKJOM8uzLY6xAxPt8qFN2BcprPl-iPz_tMt9ktmfd_E="
  ## Custom Airflow settings
  AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor" 
  AIRFLOW__CORE__DONOT_PICKLE: "false"
  AIRFLOW__CORE__DAGS_FOLDER: "/user/airflow/gitmount/dags"
  AIRFLOW__CORE__PLUGINS_FOLDER: "/user/airflow/gitmount/plugins"
  AIRFLOW__CORE__BASE_LOG_FOLDER: "/opt/airflow/logs"
  AIRFLOW__CORE__DAG_PROCESSOR_MANAGER_LOG_LOCATION: "/opt/airflow/logs/dag_processor_manager/dag_processor_manager.log"
  AIRFLOW__SCHEDULER__CHILD_PROCESS_LOG_DIRECTORY: "/opt/airflow/logs/scheduler"
  AIRFLOW__WEBSERVER__BASE_URL: "http://localhost:8080"
  # Disabling XCom pickling for forward compatibility
  AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "false"
# GIT SYNC Configurations
  GIT_SYNC_REPO: "https://github.com/dmilan77/test-airflow-dag.git"
  GIT_SYNC_BRANCH: "master"
  GIT_SYNC_ROOT: "/git"
  GIT_SYNC_DEST: "gitmount"
  GIT_SYNC_DEPTH: "1"
  GIT_SYNC_ONE_TIME: "false"
  GIT_SYNC_WAIT: "20"



  # Note: changing `Values.airflow.config` won't change the configmap checksum and so won't make
  # the pods to restart
  AIRFLOW__KUBERNETES__NAMESPACE: "airflow"
  AIRFLOW__KUBERNETES__AIRFLOW_CONFIGMAP: "airflow-configmap"
  AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "False"
  AIRFLOW__KUBERNETES__RUN_AS_USER: "50000"  
  AIRFLOW__KUBERNETES__DELETE_WORKER_PODS: "True"
  AIRFLOW__KUBERNETES__GIT_REPO: "https://github.com/dmilan77/test-airflow-dag.git"
  AIRFLOW__KUBERNETES__GIT_BRANCH: "master"
  # AIRFLOW__CORE__DAGS_FOLDER:  /user/airflow/gitmount/dags/gitmount/gitmount/dags
  # /user/airflow/gitmount/dags/parallel_dag.py
  AIRFLOW__KUBERNETES__GIT_DAGS_FOLDER_MOUNT_POINT: "/user/airflow"
  AIRFLOW__KUBERNETES__GIT_SYNC_DEST: "gitmount"
  AIRFLOW__KUBERNETES__GIT_SYNC_ROOT: "/git"
  AIRFLOW__KUBERNETES__GIT_SUBPATH: "gitmount/dags"
  AIRFLOW__KUBERNETES__GIT_SYNC_RUN_AS_USER: "50000"
  AIRFLOW__KUBERNETES__KUBE_CLIENT_REQUEST_ARGS: "{\"_request_timeout\":60}"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_IMAGE_PULL_POLICY: "IfNotPresent"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
  AIRFLOW__KUBERNETES__WORKER_CONTAINER_TAG: "1.10.10-python3.7"
  AIRFLOW__KUBERNETES__WORKER_SERVICE_ACCOUNT_NAME: "airflow"
