# Source: airflow/templates/deployments-scheduler.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow-scheduler
  template:
    metadata:
       labels:
         name: airflow-scheduler
    spec:
      restartPolicy: Always
      serviceAccountName: airflow
      volumes:
        - name: dag-folder
          emptyDir: {}      
        - name: airflow-configmap
          configMap:
            name: airflow-configmap
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.5
          volumeMounts:
          - name: dag-folder
            mountPath: /git
          envFrom:
            - configMapRef:
                name: "airflow-env"
        # - name: GIT_SYNC_DEST
        #   value: dags      
        - name: scheduler
          image: apache/airflow:1.10.10-python3.7
          volumeMounts:
          - name: dag-folder
            mountPath: /user/airflow/user  
          - name: airflow-configmap
            mountPath: /opt/airflow/airflow.cfg
            subPath: airflow.cfg
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: "airflow-env"
          env:          
            - name: POSTGRES_USER
              value: "postgres"
          command:
            - "bash"
            - "-c"
            - >
              echo "executing initdb" &&
              airflow initdb &&
              echo "executing scheduler" &&
              airflow scheduler -n -1